# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-11.10

# User packages to be built.
packages:
- .

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps: []
